package it.unimi.di.ewlab.iss.common.model.actions.facialexpressionactions.facelandmarks

enum class FaceLandmarkType {
    // La numerazione per le sopracciglia e gli occhi parte sempre da quello più vicino al naso
    LEFT_EYEBROW_1, LEFT_EYEBROW_2, LEFT_EYEBROW_3, LEFT_EYEBROW_4, LEFT_EYEBROW_5,
    RIGHT_EYEBROW_1, RIGHT_EYEBROW_2, RIGHT_EYEBROW_3, RIGHT_EYEBROW_4, RIGHT_EYEBROW_5,
    LEFT_EYE_LEFT_CORNER, LEFT_EYE_RIGHT_CORNER,
    RIGHT_EYE_LEFT_CORNER, RIGHT_EYE_RIGHT_CORNER,
    LEFT_EYE_PUPIL, RIGHT_EYE_PUPIL,
    LEFT_UPPER_EYELID_1, LEFT_UPPER_EYELID_CENTER, LEFT_UPPER_EYELID_2,
    LEFT_LOWER_EYELID_1, LEFT_LOWER_EYELID_CENTER, LEFT_LOWER_EYELID_2,
    RIGHT_UPPER_EYELID_1, RIGHT_UPPER_EYELID_CENTER, RIGHT_UPPER_EYELID_2,
    RIGHT_LOWER_EYELID_1, RIGHT_LOWER_EYELID_CENTER, RIGHT_LOWER_EYELID_2,

    NOSE_BRIDGE_1, NOSE_BRIDGE_2, NOSE_BASE, NOSE_TIP,
    NOSE_NOSTRIL_LEFT_1, NOSE_NOSTRIL_LEFT_2,
    NOSE_NOSTRIL_RIGHT_1, NOSE_NOSTRIL_RIGHT_2,

    LEFT_EAR, RIGHT_EAR,

    MOUTH_LEFT_CORNER, MOUTH_RIGHT_CORNER,
    MOUTH_UPPER_LIP_INNER_CENTER, MOUTH_UPPER_LIP_OUTER_CENTER,
    MOUTH_UPPER_LIP_LEFT, MOUTH_UPPER_LIP_RIGHT,
    MOUTH_LOWER_LIP_INNER_CENTER, MOUTH_LOWER_LIP_OUTER_CENTER,
    MOUTH_LOWER_LIP_LEFT, MOUTH_LOWER_LIP_RIGHT,

    CHIN_TIP,

    LEFT_OUTLINE, RIGHT_OUTLINE
}